# Generated by Django 3.2.13 on 2023-06-15 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awards',
            name='time',
            field=models.CharField(max_length=100),
        ),
    ]
